<?php echo $this->doctype(); ?>

<html>
  
<head>
<?php echo $this->headTitle( 'Bellow the radar groups Mapper' ) . PHP_EOL;?>
    
<?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->setCharset( 'UTF-8' );
?>
    

<!-- Scripts -->
        
<?php echo $this->headScript()
            ->prependFile( $this->basePath() . '/bootstrap/js/bootstrap.min.js')
            ->prependFile( $this->basePath() . '/bootstrap/js/jquery.min.js')
            ->prependFile( $this->basePath() . '/bootstrap/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile( $this->basePath() . '/bootstrap/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))            
; ?>
        
</head>


<body>

<div class="container">

<?php echo $this->content; ?>

</div> <!-- .container -->

</body>

<?php 
//this is causin an error
echo $this->inlineScript()
                ->prependScript( '$( document ).ready(function() {' )
                ->appendScript( "} );" ); 
                
                ?>
</html>
